[sessions]
eee=/home/silverx/Projects/ARCHTROPY/BASELINE/checkbox.sh

[text]
appendEmptyLine=true
autoBracket=false
autoReplace=false
autoSave=false
autoSaveInterval=1
darkBgColorValue=15
darkColorScheme=true
dateFormat=
dictionaryPath=
executeCommand=
executeScripts=false
font="Monospace,9,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"
inertialScrolling=false
lightBgColorValue=255
lineNumbers=true
maxSHSize=2
noIndent=false
noSyntaxHighlighting=false
noWrap=false
pastePaths=false
recentFiles=/home/silverx/Projects-3/TELEDYSKER/makeclip.sh, /home/silverx/Projects-3/LYRICS-X/CONTEXT/PROMPTS.md, /home/silverx/Projects-3/TELEDYSKER/mach.sh, /boot/loader/entries/2025-08-03_13-10-40_linux-fallback.conf, /home/silverx/BACKUP-SYSTEMD-BOOT.conf, /bin/venom, /home/silverx/Projects-3/LYRICS-X/OLD/x1, /home/silverx/Projects-3/LYRICS-X/RING-ZERO.md, /home/silverx/Projects-3/LYRICS-X/HOW-TO-LYRICS.md, /home/silverx/Projects-3/LYRICS-X/DMT.md
recentFilesNumber=10
recentOpened=false
removeTrailingSpaces=false
saveLastFilesList=false
saveUnmodified=false
selectionHighlighting=true
showEndings=false
showWhiteSpace=false
skipNonText=true
spellCheckFromStart=false
textMargin=false
textTabSize=4
thickCursor=false
vLineDistance=-80

[window]
closeWithLastTab=false
disableMenubarAccel=false
fullscreen=false
hideSearchbar=false
hideSingleTab=false
max=true
menubarTitle=false
nativeDialog=true
noMenubar=false
noToolbar=false
openInWindows=false
position=none
prefSize=@Size(909 618)
sharedSearchHistory=false
showCursorPos=false
showLangSelector=true
showStatusbar=true
sidePaneMode=false
size=@Size(952 516)
splitterPos=150
startSize=@Size(700 500)
sysIcons=false
tabPosition=0
tabWrapAround=false
