[General]
BuiltinFunction=#7e35b2
comment=#9f181c
cssValue=#79ffaf
function=#55e3ff
keyWord=#419aff
number=#ffcd00
other=#ffff00
quote=#188d4d
regex=#ffa000
type=#7f2b6e
xmlElement=#ffe100

[curLineHighlight]
value=-1

[whiteSpace]
value=90
